/**
 * Author: biebera@msoe.edu <Andrew Bieber>
 * Class: CPE 2600
 * Professor: Turney
 *
 * @file signal_alarm.c
 * @brief Demonstrates SIGALRM generated by the alarm() system call.
 * 
 * Note: AI (GPT-5) was used to generate skeletons and Javadoc-style comments
 * to explain my work thoroughly. All code written and verified by Andrew Bieber.
 */

#define _POSIX_C_SOURCE 200809L
#include <signal.h>
#include <stdio.h>
#include <unistd.h>

/** @brief Prints confirmation when SIGALRM is received. */
void handle_alarm(int sig) {
    printf("Received SIGALRM after 5 seconds (signal %d)\n", sig);
}

int main(void) {
    signal(SIGALRM, handle_alarm);
    alarm(5); // schedule alarm in 5 seconds
    printf("Alarm set. Waiting... (PID %d)\n", getpid());
    while (1) pause();
}
